### ISSUE TITLE
Pixel vs percentages

### ISSUE THREAD

**Issue by abb1991** [rafjimenez/teacozy#4]
I notice you use pixel values in your CSS:

```
.banner-image {

  display: flex;
  height: 700px;
  width: 1200px;
  background-image: url(../images/img-mission-background.jpg);
  align-items: center;
  text-align: center;

}

.banner-text {

  display: flex;
  flex-direction: column;
  justify-content: center;
  background-color: Black;
  height: 100px;
  width: 1200px;

}
```

If you haven't already, try and think through when you'd want to use definite pixel values versus fluid percentages (hint: it factors in to building a website with responsive design).

**Comment by rafjimenez** [comment]
Yes, thank you. I'm using more relative values in general now that I've completed the responsive exercises :)
